name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:22
      options: --memory=4096m

    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install AWS CLI
        run: |
          apt-get update && apt-get install -y unzip curl
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

      - name: Setup AWS credentials
        run: |
          aws configure set aws_access_key_id AKIAVVHC6D564AKQ7T45
          aws configure set aws_secret_access_key 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
          aws configure set region us-east-1

      - name: Set environment vars
        run: |
          echo "S3_BUCKET=travelo-fe-bucket" >> $GITHUB_ENV
          echo "CF_DIST_ID=E2OT941MRDL1BB" >> $GITHUB_ENV

      - name: Install Node dependencies
        working-directory: Travelo
        run: npm ci

      - name: Build project
        working-directory: Travelo
        run: npm run dev

      - name: Verify files to deploy
        working-directory: Travelo
        run: ls -la dist/

      - name: Upload to S3
        working-directory: Travelo
        run: |
          echo "Uploading to $S3_BUCKET"
          aws s3 cp dist/ s3://travelo-fe-bucket/ --recursive

      - name: Invalidate CloudFront cache
        run: |
          echo "Invalidating CloudFront"
          aws cloudfront create-invalidation --distribution-id E2OT941MRDL1BB --paths "/*"
